Tasks:
- Task:
    RemoteIps: []
    Restart: false
    ScriptLocation: local
    Source: test.sh
    TaskName: task1
    Type: script
- Task:
    RemoteIps: []
    Restart: true
    ScriptLocation: ""
    Source: try:latest
    TaskName: task2
    Type: image
- Task:
    RemoteIps:
    - Ip: 1.14.120.233
      Password: googs1025Aa1234567
      User: root
    Restart: false
    ScriptLocation: remote
    Source: ""
    TaskName: task3
    Type: script
