Tasks:
- Task:
    RemoteIps: []
    Restart: false
    ScriptLocation: local
    Source: test.sh
    TaskName: task1
    Type: script
- Task:
    RemoteIps: []
    Restart: true
    ScriptLocation: ""
    Source: try:latest
    TaskName: task2
    Type: image
- Task:
    RemoteIps:
    - Ip: xxxx
      Password: xxxxxx
      User: xxxxx
    Restart: false
    ScriptLocation: remote
    Source: ""
    TaskName: task3
    Type: script
