/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/myoperator/inspectoperator/pkg/apis/inspect/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeInspects implements InspectInterface
type FakeInspects struct {
	Fake *FakeApiV1alpha1
	ns   string
}

var inspectsResource = schema.GroupVersionResource{Group: "api.practice.com", Version: "v1alpha1", Resource: "inspects"}

var inspectsKind = schema.GroupVersionKind{Group: "api.practice.com", Version: "v1alpha1", Kind: "Inspect"}

// Get takes name of the inspect, and returns the corresponding inspect object, and an error if there is any.
func (c *FakeInspects) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Inspect, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(inspectsResource, c.ns, name), &v1alpha1.Inspect{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Inspect), err
}

// List takes label and field selectors, and returns the list of Inspects that match those selectors.
func (c *FakeInspects) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.InspectList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(inspectsResource, inspectsKind, c.ns, opts), &v1alpha1.InspectList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.InspectList{ListMeta: obj.(*v1alpha1.InspectList).ListMeta}
	for _, item := range obj.(*v1alpha1.InspectList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested inspects.
func (c *FakeInspects) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(inspectsResource, c.ns, opts))

}

// Create takes the representation of a inspect and creates it.  Returns the server's representation of the inspect, and an error, if there is any.
func (c *FakeInspects) Create(ctx context.Context, inspect *v1alpha1.Inspect, opts v1.CreateOptions) (result *v1alpha1.Inspect, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(inspectsResource, c.ns, inspect), &v1alpha1.Inspect{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Inspect), err
}

// Update takes the representation of a inspect and updates it. Returns the server's representation of the inspect, and an error, if there is any.
func (c *FakeInspects) Update(ctx context.Context, inspect *v1alpha1.Inspect, opts v1.UpdateOptions) (result *v1alpha1.Inspect, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(inspectsResource, c.ns, inspect), &v1alpha1.Inspect{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Inspect), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeInspects) UpdateStatus(ctx context.Context, inspect *v1alpha1.Inspect, opts v1.UpdateOptions) (*v1alpha1.Inspect, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(inspectsResource, "status", c.ns, inspect), &v1alpha1.Inspect{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Inspect), err
}

// Delete takes name of the inspect and deletes it. Returns an error if one occurs.
func (c *FakeInspects) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(inspectsResource, c.ns, name), &v1alpha1.Inspect{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeInspects) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(inspectsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.InspectList{})
	return err
}

// Patch applies the patch and returns the patched inspect.
func (c *FakeInspects) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Inspect, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(inspectsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Inspect{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Inspect), err
}
