/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	inspectv1alpha1 "github.com/myoperator/inspectoperator/pkg/apis/inspect/v1alpha1"
	versioned "github.com/myoperator/inspectoperator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/myoperator/inspectoperator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/myoperator/inspectoperator/pkg/client/listers/inspect/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// InspectInformer provides access to a shared informer and lister for
// Inspects.
type InspectInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.InspectLister
}

type inspectInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewInspectInformer constructs a new informer for Inspect type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewInspectInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredInspectInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredInspectInformer constructs a new informer for Inspect type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredInspectInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApiV1alpha1().Inspects(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApiV1alpha1().Inspects(namespace).Watch(context.TODO(), options)
			},
		},
		&inspectv1alpha1.Inspect{},
		resyncPeriod,
		indexers,
	)
}

func (f *inspectInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredInspectInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *inspectInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&inspectv1alpha1.Inspect{}, f.defaultInformer)
}

func (f *inspectInformer) Lister() v1alpha1.InspectLister {
	return v1alpha1.NewInspectLister(f.Informer().GetIndexer())
}
