apiVersion: apps/v1
kind: Deployment
metadata:
  name: myinspect-controller
  namespace: default
spec:
  selector:
    matchLabels:
      app: myinspect-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: myinspect-controller
    spec:
      nodeName: vm-0-16-centos # 只调度到这个节点上
      serviceAccountName: myinspect-sa # 配置service account
      containers:
        - name: myinspect
          image: inspectoperator:v1
          imagePullPolicy: IfNotPresent
          env:
            - name: "Release"
              value: "1"
          workingDir: "/app"
          command: ["./myinspectoperator"]
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myinspect-svc
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 10089
      nodePort: 31111
  selector:
    app: myinspect-controller
---