apiVersion: api.practice.com/v1alpha1
kind: Inspect
metadata:
  name: myinspect
spec:
  tasks:
    - task:
        task_name: task1
        type: script  # 可填写脚本或镜像 image script 两种
        source: test.sh # 这里预计可执行 是bash 脚本 py 脚本或是镜像。需要把东西放入./script中
        script_location: local # 可选填 local remote all 三种，分别对应 本地节点 远端节点 全部节点
        # 选取local本地节点 就不需要再填写远端ip地址
        # 远端要执行的目标node

    - task:
        task_name: task2
        type: image
        source: try:latest  # 镜像名称
#        restart: true # 用于标示是否重新执行。 如

  # 执行job cronjob
